-d /home/mii/work/MDIO/impl/gwsynthesis/MDIO.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst /home/mii/work/MDIO/src/MDIO.cst
-cfg /home/mii/work/MDIO/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
